logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url: jdbc:mysql://dental-clinic-management-system.cd0gxqcolowj.ap-northeast-1.rds.amazonaws.com:3306/dental_clinic_managenent_system?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: nxduc1506

server:
  port: 8080