logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  datasource:
#    url: jdbc:mysql://34.124.230.31:3306/dental_clinic_management_system?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#    username: root
#    password: Nxduc1506
    url: jdbc:mysql://localhost:3306/dental_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Nxduc1506@

server:
  port: 8080